"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shell$username$hostname$os$directory$git_branch$git_status$git_state $fill $time
$character
"""

add_newline = false
continuation_prompt = "[.](bright-black) "

[username]
format = "[$user@]($style)"
style_user = "green"
show_always = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[git_commit]
tag_symbol = " tag "

[git_status]
modified = "~"
deleted = "-"
conflicted = "!"
style = "red"

[git_branch]
format = " [<$branch(:$remote_branch)>]($style)"
style = "red"
# symbol = "git "
truncation_symbol = "..."

# [aws]
# symbol = "aws "
#
# [azure]
# symbol = "az "
#
# [battery]
# full_symbol = "full "
# charging_symbol = "charging "
# discharging_symbol = "discharging "
# unknown_symbol = "unknown "
# empty_symbol = "empty "
#
# [buf]
# symbol = "buf "
#
# [bun]
# symbol = "bun "
#
# [c]
# symbol = "C "
#
# [cpp]
# symbol = "C++ "
#
# [cobol]
# symbol = "cobol "
#
# [conda]
# symbol = "conda "
#
# [container]
# symbol = "container "
#
# [crystal]
# symbol = "cr "
#
# [cmake]
# symbol = "cmake "
#
# [daml]
# symbol = "daml "
#
# [dart]
# symbol = "dart "
#
# [deno]
# symbol = "deno "
#
# [dotnet]
# format = "via [$symbol($version )(target $tfm )]($style)"
# symbol = ".NET "

[directory]
format = ":[$path]($style)[$read_only]($read_only_style)"
style = "blue"
read_only = " ro"

# [docker_context]
# symbol = "docker "
#
# [elixir]
# symbol = "exs "
#
# [elm]
# symbol = "elm "
#
# [erlang]
# symbol = "erl "
#
# [fennel]
# symbol = "fnl "
#
# [fortran]
# symbol = "fortran "
#
# [fossil_branch]
# symbol = "fossil "
# truncation_symbol = "..."
#
# [gcloud]
# symbol = "gcp "
#
# [gleam]
# symbol = "gleam "
#
# [golang]
# symbol = "go "
#
# [gradle]
# symbol = "gradle "
#
# [guix_shell]
# symbol = "guix "
#
# [haskell]
# symbol = "haskell "
#
# [haxe]
# symbol = "hx "
#
# [helm]
# symbol = "helm "
#
# [hg_branch]
# symbol = "hg "
# truncation_symbol = "..."

[hostname]
format = "[$hostname]($style)[$ssh_symbol](yellow)"
ssh_only = false
ssh_symbol = '\(ssh\)'
style = "green"

# [java]
# symbol = "java "
#
# [jobs]
# symbol = "*"
#
# [julia]
# symbol = "jl "
#
# [kotlin]
# symbol = "kt "
#
# [kubernetes]
# symbol = "kubernetes "
#
# [lua]
# symbol = "lua "
#
# [nodejs]
# symbol = "nodejs "
#
# [memory_usage]
# symbol = "memory "
#
# [meson]
# symbol = "meson "
# truncation_symbol = "..."
#
# [mojo]
# symbol = "mojo "
#
# [nats]
# symbol = "nats "
#
# [netns]
# symbol = "netns "
#
# [nim]
# symbol = "nim "
#
# [nix_shell]
# symbol = "nix "
#
# [ocaml]
# symbol = "ml "
#
# [odin]
# symbol = "odin "
#
# [opa]
# symbol = "opa "
#
# [openstack]
# symbol = "openstack "

[os]
disabled = false

[os.symbols]
# AIX = '\(aix\)'
# Alpaquita = '\(alq\)'
# AlmaLinux = '\(alma\)'
# Alpine = '\(alp\)'
# Amazon = '\(amz\)'
# Android = '\(andr\)'
# AOSC = '\(aosc\)'
# Arch = '\(rch\)'
# Artix = '\(atx\)'
# Bluefin = '\(blfn\)'
# CachyOS = '\(cach\)'
# CentOS = '\(cent\)'
Debian = '\(deb\)'
# DragonFly = '\(dfbsd\)'
# Emscripten = '\(emsc\)'
# EndeavourOS = '\(ndev\)'
Fedora = '\(fed\)'
# FreeBSD = '\(fbsd\)'
# Garuda = '\(garu\)'
# Gentoo = '\(gent\)'
# HardenedBSD = '\(hbsd\)'
# Illumos = '\(lum\)'
# Kali = '\(kali\)'
Linux = '\(lnx\)'
# Mabox = '\(mbox\)'
Macos = '\(mac\)'
# Manjaro = '\(mjo\)'
# Mariner = '\(mrn\)'
# MidnightBSD = '\(mid\)'
# Mint = '\(mint\)'
# NetBSD = '\(nbsd\)'
NixOS = ''
# Nobara = '\(nbra\)'
# OpenBSD = '\(obsd\)'
# OpenCloudOS = '\(ocos\)'
# openEuler = '\(oeul\)'
# openSUSE = '\(osuse\)'
# OracleLinux = '\(orac\)'
# Pop = '\(pop\)'
# Raspbian = '\(rasp\)'
# Redhat = '\(rhl\)'
# RedHatEnterprise = '\(rhel\)'
# RockyLinux = '\(rky\)'
# Redox = '\(redox\)'
# Solus = '\(sol\)'
# SUSE = '\(suse\)'
Ubuntu = '\(ubnt\)'
# Ultramarine = '\(ultm\)'
Unknown = '\(unk\)'
# Uos = '\(uos\)'
# Void = '\(void\)'
Windows = '\(win\)'

# [package]
# symbol = "pkg "
#
# [perl]
# symbol = "pl "
#
# [php]
# symbol = "php "
#
# [pijul_channel]
# symbol = "pijul "
# truncation_symbol = "..."
#
# [pixi]
# symbol = "pixi "
#
# [pulumi]
# symbol = "pulumi "
#
# [purescript]
# symbol = "purs "
#
# [python]
# symbol = "py "
#
# [quarto]
# symbol = "quarto "
#
# [raku]
# symbol = "raku "
#
# [red]
# symbol = "red "
#
# [rlang]
# symbol = "r "
#
# [ruby]
# symbol = "rb "
#
# [rust]
# symbol = "rs "
#
# [scala]
# symbol = "scala "

[shell]
disabled = false
fish_indicator = ''
zsh_indicator = '\[zsh\] '
bash_indicator = '\[bash\] '
powershell_indicator = '\[pwsh\] '
cmd_indicator = '\[cmd\] '
unknown_indicator = '\[?\] '
format = "[$indicator]($style)"

# [shlvl]
# symbol = "shlvl "
#
# [spack]
# symbol = "spack "
#
# [solidity]
# symbol = "solidity "

[status]
symbol = "[x](bold red) "
not_executable_symbol = "noexec"
not_found_symbol = "notfound"
sigint_symbol = "sigint"
signal_symbol = "sig"

# [sudo]
# symbol = "sudo "

# [swift]
# symbol = "swift "

[time]
disabled = false
time_format = "%I:%M %p"
format = "[$time]($style)"

# [typst]
# symbol = "typst "
#
# [vagrant]
# symbol = "vagrant "
#
# [terraform]
# symbol = "terraform "
#
# [xmake]
# symbol = "xmake "
#
# [zig]
# symbol = "zig "
